<?xml version="1.0" encoding="utf-8"?><Database Name="library-app" Class="LibraryDCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-QK7K1DR;Initial Catalog=library-app;Integrated Security=True" SettingsObjectName="library_app.Properties.Settings" SettingsPropertyName="library_appConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="role_id" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="user_issueBook" Member="issueBooks" ThisKey="id" OtherKey="user_id" Type="issueBook" />
      <Association Name="role_user" Member="role" ThisKey="role_id" OtherKey="id" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.role" Member="roles">
    <Type Name="role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="role_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="role_user" Member="users" ThisKey="id" OtherKey="role_id" Type="user" />
    </Type>
  </Table>
  <Table Name="dbo.issueBooks" Member="issueBooks">
    <Type Name="issueBook">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="book_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="issued_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="issue_at" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="due_at" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="return_at" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="user_issueBook" Member="user" ThisKey="user_id" OtherKey="id" Type="user" IsForeignKey="true" />
      <Association Name="book_issueBook" Member="book" ThisKey="book_id" OtherKey="id" Type="book" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.book" Member="books">
    <Type Name="book">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="author" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="publisher" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="published" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="pages" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="available_copies" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="added_at" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lastIssued_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="book_issueBook" Member="issueBooks" ThisKey="id" OtherKey="book_id" Type="issueBook" />
    </Type>
  </Table>
</Database>